name: edlfs
channels:
- conda-forge
dependencies:
- python=3.9
- xarray>=0.19
- fsspec>=2022.1.0
- dask>=2022.1
- matplotlib-base>=3.3
- cartopy>=0.18.0
- netcdf4>=1.5
- h5netcdf>=0.11
- h5py>=3.2
- zarr>=2.9.5
# documentation and profiling
- jupyterlab>=3
- mkdocs>=1.2
- mkdocs-material>=7.1, <9.0
- markdown-include>=0.6
- mkdocstrings>=0.18
- mkdocs-jupyter=0.18.0
- pymdown-extensions=9.2
- pygments=2.11.1
# build and test
- setuptools>=61
- setuptools_scm>=6.2
- build
# Necessary pip packages
- pip
- pip:
  - earthdata
